version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "23:00"
  open-pull-requests-limit: 10
  assignees:
  - VitalyTartynov
  ignore:
  - dependency-name: webpack
    versions:
    - 5.17.0
    - 5.19.0
    - 5.21.2
    - 5.22.0
    - 5.24.0
    - 5.24.2
    - 5.24.4
    - 5.26.0
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.32.0
    - 5.34.0
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
